{%echo '<?php'%} 
/**
 * Generated by bookproto
 * Do't modify this file directly, new inherited class file instead.
 */

namespace {%echo convertPackage($package);%} 
{
    {% include insertTpl('nestedClass'); %}
}

{% foreach ($nestedMessages as $msg): %}
namespace {%echo getPackage($msg);%} 
{
    {% insertNestedClass($msg); %}
}

{% endforeach; %}

{% foreach ($enums as $enum): %}
namespace {%echo getPackage($enum);%} 
{
    {% insertNestedEnum($enum); %}
}

{% endforeach; %}