///
/// Generated by bookproto
/// Do't modify this file directly, new partial class file instead.
///
using System;
using System.IO;
using System.Collections.Generic;
using bookrpg.net;
using bookrpg.net.protobuf;
using bookrpg.utils;

{% if ($package != ''): %}
namespace {%$package%} 
{
{% endif; %}
    {% include insertTpl('nestedClass'); %}
{% if ($package != ''): %}
}
{% endif; %}